---
title: "0914 빅데이터 분석기사"
format: html
editor: visual
---

##### 데이터의 정의

    -   데이터 : 가공되기 전의 객관적 수치 또는 기호

    -   정보 : 데이터의 가공 및 처리를 통해 도출된 현상

    -   지식 : 정보의 구조화를 통해 도출되는 고유의 아이디어

      -   암묵지 : 개인에게 축적된 내면화된 지식으로 공통화, 내면화 과정이 작용

      -   형식지 : 언어나 문서로 표준화 및 형상화된 지식으로 표출화, 연결화 과정이 작용

            -   지식의 변환 : 공통화(암->암), 표출화(암->형), 내면화(형->암), 연결화(형->형)

    -   지혜 : 지식의 축적과 아이디어가 결합된 창의적 산물

##### 빅데이터가 만든 변화

    -   사전처리 -> 사후처리

    -   표본조사 -> 전수조사

    -   질 -> 양

    -   인과 관계 -> 상관관계

##### 빅데이터의 위기 요인과 통제 방안

    -   사생활 침해

    -   책임 원칙 훼손

    -   데이터 오용

##### 빅데이터 조직 구조

    -   집중 구조 :  각 부서별로 분석을 진행하며 전사 분석업무를 별도의 분석 전담 조직에서 담당. 분석업무가 이중화, 이원화될 수 있다.

    - 기능 구조 : 각 부서별로 분석을 진행, 별도의 분석 조직이 없어 전사적 핵심분석이 어렵고, 과거 실적 분석에 국한될 가능성이 크다

    - 분산 구조 : 분석 조직 인력들을 현업부서로 직접 배치하여 분석업무를 수행, 분석 결과에 따른 신속한 활동이 가능하며, Best Practice의 공유가 가능하여 분석 수준을 상향 평준화시킬 수 있다. 각 부서의 분석업무와 역할 분담을 명확히 해야 한다.

##### 개인정보 비식별화 기술

-   가명 처리 : 휴리스틱 가명화 , K-익명화, 암호화, 교환 방법 등. 개인 식별이 가능한 데이터를 다른 값으로 대체하는 기법

-   총계처리 : 총합, 부분합, 라운딩, 재배열 등. 개인 정보에 통계값을 적용하여 개인을 특정할 수 없게 하는 기법

-   데이터 삭제 : 식별자 삭제, 부분 삭제, 레코드 삭제 등. 특정 데이터 값을 삭제하는 기법

-   데이터 범주화 : 범주화, 랜덤 라운딩, 범위화 등. 식별 값을 해당 그룹의 대푯값이나 구간값으로 변환하는 기법

-   데이터 마스킹 : 임의 잡음 추가, 공백 및 대체 방법이 있으며, 식별값의 전체 또는 부분을 대체값으로 변환하는 기법
