---
title: "2-15강 회귀모델의 설명력"
author: "BBJ"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
```

## 2-15장 회귀모델의 설명력
▪ mtcars 데이터셋
  • 자동차의 연비에 대한 데이터셋(1074년): 변수 11개, 관측값 32개
    - mpg: 연비 (miles/gallon)
    - cyl: 실린더 개수
    - disp: 배기량 (cu. in.)
    - hp: 마력
    - drat: 기어비(후방 차축 비율)
    - wt: 중량 (1000 lbs)
    - qsec: ¼ 마일 시간
    - vs: 엔진 (0=V-모양, 1=straight)
    - am: 트랜스미션 (0=자동, 1=수동)
    - gear: 전방 기어의 개수
    - carb: 기화기의 개수
```{r}
df <- mtcars
str(df)
df <- mtcars[, c(1:6)] # mpg ~ wt
str(df)

plot(df, col = 'green')
cor(df)

# install.packages('corrplot')
# library(corrplot)

library(corrgram)
corrgram(df)

# 다중 회귀분석
lm(mpg ~ ., data = df)
model <- lm(mpg ~ ., data = df)
summary(model) # 귀무가설 기각 가능한 건 wt만? 0.05보다 크기 때문
# Adjusted R-squared:  0.8227 관계 높음 

# models <- lm(mpg ~ disp, wdrat + hp + wt)


library(car)
scatterplotMatrix(df, pch = 19, col = "steelblue", cex = 1.2,
regLine = list(method = lm, lwd = 2, col = "tomato"),
smooth = list(smoother = loessLine, spread = FALSE, 
lwd.smooth = 2, col.smooth = "orange"))
```

# 연습문제
  * Kallge House Price 데이터에서
  * 다중 선형 회귀의 변수 선택을 통해
  * 최적의 독립 변수 조합을 찾아보시오.
  * 1. 전진선택법으로 찾은 조합은? R2, Adjusted R2 값은?
  * 2. 후진선택법으로 찾은 조합은? R2, Adjusted R2 값은?
```{r}

```

  






























