---
title: "Untitled"
author: "BBJ"
date: "2022-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ▪ 혼동 행렬: Confusion Matrix
  • 이진 분류기의 분류 결과를 2 × 2 행렬로 표시한 행렬
  • 이진 분류기가 분류(예측)할 때, 얼마나 많이 헷갈렸는가를 나타냄

```{r}
# 팔머스펭귄데이터로 결측치 제거
library(palmerpenguins)
pg <- penguins
pg <- pg[complete.cases(pg), -8]
str(pg)
dim(pg)

# 이항 로지스틱 회귀분석
pg$is.adelie <- factor(
  ifelse(pg$species == 'Adelie', 'YES', 'NO'))
barplot(table(pg$is.adelie))

str(pg)
pg <- pg[, -1]
str(pg)

model <- glm(is.adelie ~ ., data = pg,
             family = binomial(link = "logit"))
summary(model)
# predict(model)

model$fitted
pg$pred <- factor(ifelse(
  model$fitted.values > 0.5, "Yes", "No"))
table(pg$is.adelie, pg$pred)
```

```{r}
# 버지니카인가, 아닌가? 이항 로지스틱 회귀분석

df <- iris
df$Species <- factor(ifelse(
  df$Species == "virginica", "Yes", "No")) # 실제값

model <- glm(Species ~ ., data = df,
             family = binomial(link = "logit"))
summary(model)

df$pred <- factor(ifelse(
  model$fitted.values > 0.5, "Yes", "No")) # 예측값

tab <- table(df$Species, df$pred)
tab

TP <- tab[2, 2] # True, Positive
TN <- tab[1, 1]
FP <- tab[2, 1]
FN <- tab[1, 2] # False, Negative

# 분류 모델의 성능 평가 지표: Evaluation Metric
accuracy <- (TP + TN) / (TP + TN + FP + FN) # 정확도
accuracy

precision <- TP / (TP + FP) # 정밀도

recall <- TP / (TP + FN) # 재현율

F1.score <- (2 X precision) / (precision + recall)# 정밀도와 재현율의 조화평균

# install.packages("pROC")
library(pROC)
roc(Species ~ model$fitted.values, data = df,
    plot = TRUE, main = "ROC CURVE", col = "tomato")
```





















