---
title: "Loan payments data"
format: html
editor: visual
---

## 박병준

| 변수명             | 해석(의미)                                       |
|--------------------|--------------------------------------------------|
| **Loan_ID**        | 대출한 고객의 고유한 ID                          |
| **loan_status**    | 이번 분석의 타겟 변수, 상환 여부를 나타냄        |
| **Principal**      | 고객이 대출받은 금액                             |
| **terms**          | 대출금 지급까지 걸린 기간                        |
| **effective_date** | 실제 계약 효과가 발휘하기 시작한 날짜            |
| **due_date**       | 대출금 납부 기한 날짜                            |
| **paid_off_time**  | 고객이 은행에 모두 상환한 날짜, 시간             |
| **past_due_days**  | 고객이 은행에 대출금을 모두 상환하는데 걸린 기간 |
| **age**            | 고객의 나이                                      |
| **education**      | 고객의 교육 수준                                 |
| **Gender**         | 고객의 성별                                      |

데이터 확인, factor로 변환

```{r}
df <- read.csv('Loan payments data.csv')
df <- df[, -1] # Loan_ID 컬럼 삭제
df
# str(df)

cat("\n")

df$loan_status <- factor(df$loan_status)
df$effective_date <- factor(df$effective_date)
df$due_date <- factor(df$due_date)
df$paid_off_time <- factor(df$paid_off_time)
df$education <- factor(df$education)
df$Gender <- factor(df$Gender)
str(df)
```

결측치 확인

```{r}
library(VIM)
aggr(df, prop = FALSE, # 빈도수 또는 비율 출력, FALSE : 빈도
     combined = TRUE, # missing value 있는 plot과 없는 plot 2개를 하나로 결합할지 안 할지
     numbers = TRUE, # plot에 정확한 count number 출력 여부
     sortVars = TRUE, # console window에 변수 별로 missing value count를 출력할지 안 할지
     sorCombs = TRUE) # 결합한 plot의 출력값에서 NA개수를 우선해서 출력
```

```{r}
df$SoF <- factor(ifelse(
  df$loan_status == "PAIDOFF", "SUCCESS", "FAILURE"))
levels(df$SoF) # SUCCESS or FAILURE

model <- glm(SoF ~ ., data = df,
             family = binomial(link = "logit"))
summary(model)

```
